development:
  adapter: mysql2
  database: yogavideo1_development
  username: root
  password: Fr33d0m!
  host: localhost
test:
  adapter: mysql2
  database: yogavideo1_test
  username: root
  password: Fr33d0m!
  host: localhost
production:
  adapter: mysql2
  database: yogavideo1_production
  username: root
  password: Fr33d0m!
  host: localhost
